drivers: usb: notify: fix mismatch after kCFI backport
Fixes:

WARNING: modpost: drivers/usb/notify/usb_notifier_qcom.lto.o(.exit.data+0x0): Section mismatch in reference from the variable __UNIQUE_ID___addressable_cleanup_module329 to the function .init.text:cleanup_module()
The variable __exitdata __UNIQUE_ID___addressable_cleanup_module329 references
a function __init cleanup_module().
This is often seen when error handling in the exit function
uses functionality in the init path.
The fix is often to remove the __init annotation of
cleanup_module() so it may be used outside an init section.

ERROR: modpost: Section mismatches detected.
Set CONFIG_SECTION_MISMATCH_WARN_ONLY=y to allow them.
make[2]: *** [/home/ylrcy/android_kernel_samsung_b4q/kernel_platform/msm-kernel/scripts/Makefile.modpost:168: modules-only.symvers] Error 1
make[2]: *** Deleting file 'modules-only.symvers'
make[1]: *** [/home/ylrcy/android_kernel_samsung_b4q/kernel_platform/msm-kernel/Makefile:1909: modules] Error 2
make: *** [/home/ylrcy/android_kernel_samsung_b4q/kernel_platform/msm-kernel/Makefile:196: __sub-make] Error 2

Signed-off-by: xfwdrev <74693315+xfwdrev@users.noreply.github.com>